name: .NET-CI

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: dir
    - name: Build
      run: dotnet build --verbosity diag
    - name: Test
      run: dotnet test --no-build --verbosity normal
