name: .NET-CI

on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: dotnet build --verbosity normal
    - name: Test
      run: dotnet test --no-build --verbosity normal
